/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

"use strict";var e=require("@lexical/extension"),t=require("lexical");const n={bold:"bold",italic:"italic",strikeThrough:"strikethrough",subscript:"subscript",superscript:"superscript",underline:"underline"},i=Symbol.for("@lexical/dragon/WindowState");function o(e,t,n){const o=function(e){let t=e[i];return void 0===t&&(t={dispose:()=>{},editors:new Map,installs:new Set},e[i]=t),t}(e);if(0===o.installs.size){const t=l.bind(e);e.addEventListener("message",t,!0),o.dispose=()=>{e.removeEventListener("message",t,!0)}}if(o.installs.add(t),n){const e=o.editors.get(n)||new Set;e.add(t),o.editors.set(n,e)}return s.bind(null,e,o,t,n)}function s(e,t,n,o){if(o){const e=t.editors.get(o);e&&e.delete(n)&&0===e.size&&t.editors.delete(o)}t.installs.delete(n)&&0===t.installs.size&&(t.dispose(),delete e[i])}function r(e){return e&&e.ownerDocument.defaultView}function a(t){const n=e.watchedSignal(()=>r(t.getRootElement()),e=>t.registerRootListener(t=>{e.value=r(t)}));return e.effect(()=>{const e=n.value;if(e)return o(e,Symbol("@lexical/dragon/editorInstall"),t)})}function l(e){if(e.origin!==this.location.origin)return;const o=function(e){const n=e[i];if(void 0===n)return null;const o=t.getEditorPropertyFromDOMNode(t.getActiveElementDeep(e.document));return t.isLexicalEditor(o)&&n.editors.has(o)?o:null}(this);if(null===o)return;const s=e.data;if("string"==typeof s){let i;try{i=JSON.parse(s)}catch(e){return}if(i&&"nuanria_messaging"===i.protocol&&"request"===i.type){const s=i.payload;if(s&&"makeChanges"===s.functionId){const i=s.args;if(Array.isArray(i)){const[s,r,a,l,d,c]=i;if(![s,r,l,d].every(Number.isFinite)||"string"!=typeof a&&-1!==a)return;o.update(()=>{const i=t.$getSelection();if(t.$isRangeSelection(i)){const o=i.anchor;let u=o.getNode(),f=0,g=0;if(t.$isTextNode(u)&&s>=0&&r>=0&&(f=s,g=s+r,i.setTextNodeRange(u,f,u,g)),"string"!=typeof a||f===g&&""===a||(i.insertRawText(a),u=o.getNode()),t.$isTextNode(u)){const e=u.getTextContentSize();f=Math.min(Math.max(l,0),e),g=l<0||d<0?f:Math.min(l+d,e),i.setTextNodeRange(u,f,u,g)}if("string"==typeof c&&d>0&&!i.isCollapsed()){const e=n[c];void 0!==e&&i.formatText(e)}e.stopImmediatePropagation()}})}}}}}const d=/* @__PURE__ */t.defineExtension({build:(t,n,i)=>e.namedSignals(n),config:/* @__PURE__ */t.safeCast({disabled:"undefined"==typeof window}),name:"@lexical/dragon",register:(t,n,i)=>e.effect(()=>i.getOutput().disabled.value?void 0:a(t))});exports.DragonExtension=d,exports.installDragonSupport=function(e=function(){return"undefined"!=typeof window?window:void 0}()){return e?o(e,Symbol("@lexical/dragon/globalInstall"),void 0):()=>{}},exports.registerDragonSupport=a;
